// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnimtextController from "./animtext_controller"
application.register("animtext", AnimtextController)

import BannerController from "./banner_controller"
application.register("banner", BannerController)

import CategoryController from "./category_controller"
application.register("category", CategoryController)

import FooterController from "./footer_controller"
application.register("footer", FooterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ScrollController from "./scroll_controller"
application.register("scroll", ScrollController)
